### PR TITLE
Flash trace and exit

### PR DESCRIPTION
**Pull request by ciscoheat**
Here's a PR with flash tracing and exiting if some consideration is taken in the code:

To exit, `flash.system.System.exit(status);` is required.
To trace, `flash.Lib.trace(data);` seems to be required (normal trace didn't seem to work).

How to make it easy enabling this special mode for travix?

### CODE REVIEW

**Comment by kevinresol** [comment]
I have no idea about flash. But seems that having something is always better than having nothing.
@back2dos?

**Comment by back2dos** [comment]
I'm fine with letting the user deal with exiting and logging for now. Most test frameworks seem to have their own opinion about how this should be done, so I don't want to get in their way. As @kevinresol said, it's better than nothing.

@ciscoheat This is nothing I strongly care about, so if you could take care of it, that would be great. I have given you the necessary access to proceed as you see fit. If you can make this work for you and buddy and all the tests that you have, I think it's safe to assume it works ;)

**Comment by ciscoheat** [comment]
Thanks, sure I'll take care of business!

**Comment by back2dos** [comment]
Awesome, thanks!

**Comment by ciscoheat** [comment]
It's pretty much working now, and I've added buddy tests for all targets as well. Unfortunately there seems to be some travis issues right now, so the build is failing...

Anyway, will this be the default for flash execution? If someone doesn't exit from flash in their code, then the travix script will be stuck, since the flash code will not only compile but also run. Of course that could be noted in the docs, just thinking about backwards compatibility.

**Comment by back2dos** [comment]
Let's see if anyone complains. I guess people who use buddy have this handled for them anyway (right?).

The [doc for `run flash`](https://github.com/back2dos/travix#building) will need to be updated anyway, so that's a good place to put a warning.

**Comment by ciscoheat** [comment]
Yes they have it handled. :) I'll be back soon!

**Comment by ciscoheat** [comment]
It was a nightmare to fix, but finally it works on both 3.2.1 and 3.3. I've merged and updated the docs.

**Comment by back2dos** [comment]
Awesome! Thanks a lot ;)

**Pull request closed without merging**
