### PR TITLE
Testing with Vagrant

### PR DESCRIPTION
**Pull request by ciscoheat**
[Vagrant](https://www.vagrantup.com/) is a nice way to get up and running quickly for development. Maybe we can add this to the repo? Then testing travix on all targets will be as simple as:

```
git clone https://github.com/back2dos/travix.git
cd travix
vagrant up
vagrant ssh
```

### CODE REVIEW

**Comment by back2dos** [comment]
I'm not at all familiar with vagrant, but I wonder about the practicality of installing everything beforehand. Won't travix do that on demand?

**Comment by ciscoheat** [comment]
For travix it *could* work, but there could be some small problems. It's a general solution from [viagrant](https://github.com/ciscoheat/viagrant) that works for any haxe project. I just added a few lines to install travix.

**Comment by back2dos** [comment]
Ok, sure, why not :)

**Comment by ciscoheat** [comment]
Nice! @jdonaldson, this should make it easy to get started with #22 if you need it.

**Pull request merged**
