### PR TITLE
Lua is working now with buddy 2.6.2 or later.

### PR DESCRIPTION
**Pull request by ciscoheat**
With help from @jdonaldson, buddy has been patched to making Lua work, which means Lua testing should now work with travix!

### CODE REVIEW

**Comment by back2dos** [comment]
You guys rock!

**Comment by nadako** [comment]
I tried this and it can't download apt repo files for some reason (https://travis-ci.org/nadako/hxjsonast/jobs/198196984#L424). Probably it's a temporary issue with the PPA, but so far I restarted the build 3 times and it still persists. Could it be that PPA was moved or something?

**Comment by nadako** [comment]
Oh wait, it tries to download for `trusty` from a `precise-backports` repo, so I guess it's something to be fixed in travix after all.

**Comment by ciscoheat** [comment]
Yep, I understand the problem now. If we declare precise as unsupported, it's an easy fix, simply remove line 10-11 in `LuaCommand.hx` (the apt commands about the precise backport). The problem is that `cmake` wasn't up-to-date enough to build the required lua modules on precise.

If this is ok for you @back2dos I'll make a PR.

**Pull request merged**
