### PR TITLE
Removed ubuntu precise-specific fix.

### PR DESCRIPTION
**Pull request by ciscoheat**
If we want to stop supporting precise, which I think we should do, this will fix the Lua problem.

### CODE REVIEW

**Comment by back2dos** [comment]
Uhm, I have absolutely no clue here. Is there any advantage in supporting precise?

I can't think of one so for me it's absolutely fine to go ahead with this. If possible, I would prefer to give the user an informative error though (instead of just letting it fail on its own).

**Comment by ciscoheat** [comment]
It's nice to those still using it, but since it's close to ending its LTS, I don't think it's worth the hassle: https://wiki.ubuntu.com/LTS (12.04)

**Comment by nadako** [comment]
Couldn't you just check for ubuntu version and conditionally add that repo?

**Comment by ciscoheat** [comment]
That's an option. Since Travis still can run on precise, maybe it's worth it. I hope this doesn't lead to a nightmare of Ubuntu release management though. :) I'll update the PR soon.

**Comment by nadako** [comment]
I wonder what that means: https://travis-ci.org/nadako/hxjsonast/jobs/201551798#L273
```
sh: 1: [: trusty: unexpected operator
```

Also the test apparently fails with exit code 0 there,but I guess that's `utest`'s fault.

**Comment by back2dos** [comment]
Some ~~research~~ google'n'stackoverflow led me to believe that it's because [you're executing a bash syntax on plain sh](http://stackoverflow.com/a/3411061/111466), which I believe is happening [in the precise check](https://github.com/back2dos/travix/blob/master/src/travix/commands/LuaCommand.hx#L9).

I suppose you could `lsb_release -s -c > distro.txt` and check its content from Haxe. But then again this is *way* out of my comfort zone ^^

**Comment by nadako** [comment]
Meh, so it's something wrong with my `.travis.yml`? Oh well, I'll look into it later.

**Comment by back2dos** [comment]
No, no, sorry. I mean @ciscoheat is relying on bash syntax for the check against precise but it winds up being interpreted as plain sh syntax and thus fails.

As far as I understand it, you can ignore the error for now, because you're on trusty anyway ;)

**Comment by ciscoheat** [comment]
Oh, this never ends... and I was thinking about it! Well, I'll patch it.

**Pull request merged**
