### PR TITLE
Add brew support (closes #2)

### LINKED ISSUE #2: Mac: brew python3 and mono
required for python and cs target

### PR DESCRIPTION
**Pull request by kevinresol**
closes #2

### CODE REVIEW

**Comment by back2dos** [comment]
Well using `aptGet` to `brew` seems a bit of a stretch, but if it works, I'll take it. Thanks! :)

**Comment by kevinresol** [comment]
Thanks for taking it, would you mind making a release to haxelib so that we can enjoy it?

**Comment by back2dos** [comment]
Good point. Just did that. 

I've given you write access here and on haxelib. I can use all the help I can get on this project, because I really suck at this kind of stuff. No pressure though ;)

**Comment by kevinresol** [comment]
I suck too, I'm just basing on your initial effort! We should probably invite @andyli to here!

**Comment by back2dos** [comment]
Well, I imagine he has more than enough things on his plate, but I've added him too. Sorry for the noise @andyli. Feel free to remove yourself if you have no interest to contribute to this contraption ;)

**Comment by andyli** [comment]
Hey, thanks for adding me!
I noticed travix and I like the idea. I just haven't had time to check it out in depth.
I'll keep the commit right as my honer for now :)

**Pull request merged**
