### PR TITLE
Flash version updated

### PR DESCRIPTION
**Pull request by ciscoheat**
According to ciscoheat/buddy#70 flash version 28 doesn't work anymore, so here's a patch.

### CODE REVIEW

**Comment by ciscoheat** [comment]
Was haxelib updated with this one? It still seems to use version 28 in travis.

**Comment by ciscoheat** [comment]
@back2dos Do you mind doing a quick update for this one so it works again on travis?

**Comment by back2dos** [comment]
Uh, yeah, sorry. I was hoping you'd make updates yourself as you see fit https://github.com/back2dos/travix/blob/master/haxelib.json#L15 ;)

**Comment by ciscoheat** [comment]
I can do that, of course. :) But is there any build/package process? I don't want to mess things up on haxelib.

**Comment by back2dos** [comment]
Well, in theory you can just tag and push, but since Flash fails on Mac, you have to do it yourself. Or we could just disable flash on Mac: https://github.com/back2dos/travix/issues/95

**Comment by ciscoheat** [comment]
I made a zip file, but when submitting to haxelib I get a strange error message, that I mentioned on gitter.

**Pull request merged**
